name: fl_hover
description: A comprehensive Flutter package providing beautiful hover effects and animations for web and desktop applications.
version: 1.1.1
homepage: https://github.com/alirezat66/fl_hover
repository: https://github.com/alirezat66/fl_hover
issue_tracker: https://github.com/alirezat66/fl_hover/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  # liquid_glass_renderer: ^0.1.1-dev.10  # Temporarily removed for stable release

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
topics:
  - animation
  - hover
  - web
  - flutter

platforms:
  web:
  windows:
  linux:
  macos:
